name: Publish to NPM with Provenance

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    # Add permissions for OIDC token required for provenance
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm run build

      - name: Publish to NPM with provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: npm publish --provenance

      - name: Verify provenance (optional)
        run: |
          echo "Package published with provenance. Users can verify with:"
          echo "npm audit signatures"

# Instructions for use:
# 1. Copy this file to .github/workflows/publish.yml in your package
# 2. Update the node-version if needed
# 3. Ensure your PUBLISH_TOKEN secret is configured
# 4. Make sure your package.json has the correct repository URL
# 5. If using npm instead of pnpm, replace pnpm commands with npm ci and npm run build
